replicaCount: 1

image:
  repository: me1vin/lesta-end
  tag: 0.0.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: lesta-end.app
      paths:
        - path: /
          pathType: Prefix
  tls: []

env: 
  - name: FLASK_APP
    value: app:app

secrets: 
  - name: SQLALCHEMY_DATABASE_URI
    secretName: lesta-db-secret
    secretKey: DATABASE_URL
