replicaCount: 1

image:
  repository: me1vin/lesta-end
  tag: 0.0.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - host: lesta-end.app
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: lesta-end-tls     # cert-manager создаст сам
      hosts:
        - lesta-end.app

#ingress:
#  enabled: true
#  hosts:
#    - host: lesta-end.app
#      paths:
#        - path: /
#          pathType: Prefix
#  tls: 
#    - hosts:
#        - lesta-end.app
#      secretName: lesta-end-tls

env: 
  - name: FLASK_APP
    value: routes:app

secrets: 
  - name: DB_URL
    secretName: lesta-db-secret
    secretKey: DB_URL
