replicaCount: 1

image:
  repository: me1vin/lesta-end
  tag: 0.0.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: lesta-end.app
      paths:
        - path: /
          pathType: Prefix
  tls: 
    - hosts:
        - lesta-end.app
      secretName: lesta-end-tls

env: 
  - name: FLASK_APP
    value: routes:app

secrets: 
  - name: DB_URL
    secretName: lesta-db-secret
    secretKey: DB_URL
