apiVersion: apps/v1
kind: Deployment
metadata:
  name: lesta-end
  namespace: app
  labels:
    app: lesta-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lesta-end
  template:
    metadata:
      labels:
        app: lesta-end
    spec:
      containers:
        - name: lesta-end
          image: me1vin/lesta-end:0.0.1
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_APP
              value: app:app
            - name: SQLALCHEMY_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: lesta-db-secret
                  key: DATABASE_URL
      restartPolicy: Always
