apiVersion: v1
kind: Service
metadata:
  name: {{ include "lesta-end.fullname" . }}
  labels:
    app: {{ include "lesta-end.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
  selector:
    app: {{ include "lesta-end.name" . }}

